if(NOT TARGET protocol)
add_subdirectory(protocol/utility)
add_subdirectory(protocol/public)
    add_subdirectory(protocol/mpc)
    IF(ROSETTA_ENABLES_PROTOCOL_ZK)
        add_subdirectory(protocol/zk)
    ENDIF()
    if(ROSETTA_ENABLES_PROTOCOL_PSI)
        #add_subdirectory(protocol/psi)
    endif()
endif()
