
# libraries version number
set(MAJOR_VERSION   1)
set(MINOR_VERSION   0)
set(PATCH_VERSION   0)
set(XXXXX_VERSION   0)
set(SO_VERSION      ${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}.${XXXXX_VERSION})
set(SDK_VERSION     ${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}.${XXXXX_VERSION})
